baseURL = "https://thetimesweeper.com"
title = "The Time Sweeper"
author = "Tomás Carvalho"
copyright = "Copyright © 2023-2034"
languageCode = "en"

[params]
  favicon = "images/favicon.png"
  images = ["images/share.png"]
  title = "The Time Sweeper"

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]


[permalinks]
  writings = "/:slug/"
  tags = "/writings/:slug"
