baseURL = "https://thetimesweeper.com"
title = "The Time Sweeper"
author = "Tomás Carvalho"
copyright = "Copyright © 2023-2034"
languageCode = "en"

[params]
  description = "Beyond Good and Evil"
  favicon = "images/favicon.png"
  images = ["images/share.png"]
  title = "The Time Sweeper"